import js from '@eslint/js';
import tseslint from 'typescript-eslint';

const rendererGlobals = {
  window: 'readonly',
  document: 'readonly',
  localStorage: 'readonly',
  Terminal: 'readonly',
  FitAddon: 'readonly',
  WebglAddon: 'readonly',
  SearchAddon: 'readonly',
  ResizeObserver: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  clearTimeout: 'readonly',
  requestAnimationFrame: 'readonly',
  console: 'readonly',
  agentDesk: 'readonly',
  CustomEvent: 'readonly',
  navigator: 'readonly',
  initSettings: 'readonly',
  getSettings: 'readonly',
  getSetting: 'readonly',
  setSetting: 'readonly',
  fetch: 'readonly',
  loadProfiles: 'readonly',
  saveProfiles: 'readonly',
  getProfiles: 'readonly',
  createTerminalFromProfile: 'readonly',
  getNotificationRules: 'readonly',
  getSnippets: 'readonly',
  Audio: 'readonly',
  KeybindingManager: 'readonly',
  ShellIntegration: 'readonly',
  eventBus: 'readonly',
  agentParser: 'readonly',
  eventStream: 'readonly',
  AbortSignal: 'readonly',
  WebLinksAddon: 'readonly',
  ImageAddon: 'readonly',
  switchToTerminal: 'readonly',
  switchView: 'readonly',
  getThemeById: 'readonly',
  applyThemeColors: 'readonly',
  clearThemeColors: 'readonly',
  getAllThemes: 'readonly',
  DOMParser: 'readonly',
  URL: 'readonly',
  Event: 'readonly',
  MutationObserver: 'readonly',
  performance: 'readonly',
  cancelAnimationFrame: 'readonly',
  showToast: 'readonly',
  agentDeskBridge: 'readonly',
  morphdom: 'readonly',
  CSS: 'readonly',
  saveWorkspace: 'readonly',
  loadWorkspaces: 'readonly',
  showWorkspaceLoadPicker: 'readonly',
  _renderThemesSection: 'readonly',
  deleteCustomTheme: 'readonly',
  exportThemeJSON: 'readonly',
  importThemeJSON: 'readonly',
  saveCustomTheme: 'readonly',
  renderTemplatesSection: 'readonly',
  confirm: 'readonly',
};

const rendererRules = {
  'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
  '@typescript-eslint/no-unused-vars': 'off',
  'no-redeclare': 'off',
  'no-control-regex': 'off',
};

const nonModuleFiles = [
  'src/renderer/settings.js',
  'src/renderer/keybinding-manager.js',
  'src/renderer/shell-integration.js',
  'src/renderer/theme-manager.js',
  'src/renderer/event-bus.js',
  'src/renderer/agent-parser.js',
  'src/renderer/event-stream.js',
  'src/renderer/replay.js',
  'src/renderer/theme-init.js',
];

const esModuleFiles = [
  'src/renderer/app.js',
  'src/renderer/state.js',
  'src/renderer/terminals.js',
  'src/renderer/layout.js',
  'src/renderer/keybinds.js',
  'src/renderer/search.js',
  'src/renderer/views.js',
  'src/renderer/commands.js',
  'src/renderer/context-menus.js',
  'src/renderer/notifications.js',
  'src/renderer/linking.js',
  'src/renderer/agent-features.js',
  'src/renderer/recording-ui.js',
  'src/renderer/drag-drop.js',
  'src/renderer/dashboard.js',
  'src/renderer/workspaces.js',
  'src/renderer/per-terminal.js',
  'src/renderer/system-monitor.js',
  'src/renderer/agent-monitor.js',
  'src/renderer/batch-launcher.js',
  'src/renderer/templates.js',
  'src/renderer/comm-graph.js',
  'src/renderer/global-search.js',
  'src/renderer/onboarding.js',
  'src/renderer/feature-tips.js',
  'src/renderer/dom-utils.js',
  'src/renderer/views/comm-view.js',
  'src/renderer/views/tasks-view.js',
  'src/renderer/views/knowledge-view.js',
  'src/renderer/views/discover-view.js',
];

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      'no-console': 'off',
    },
  },
  {
    files: nonModuleFiles,
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: rendererGlobals,
    },
    rules: rendererRules,
  },
  {
    files: esModuleFiles,
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: rendererGlobals,
    },
    rules: rendererRules,
  },
  {
    files: ['src/renderer/dashboard-injectors/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: rendererGlobals,
    },
    rules: rendererRules,
  },
  {
    ignores: ['dist/', 'release/', 'node_modules/', 'resources/', 'src/renderer/vendor/'],
  },
];
